marlin/sailfish: Add display packages required for CAF.
This will fix:
error: frameworks/native/services/surfaceflinger/tests/unittests/Android.bp:15:1:
"libsurfaceflinger_unittest" depends on undefined module "libqdMetaData.system"

Signed-off-by: spezi77 <spezi7713@gmx.net>